apiVersion: v1
kind: Service
metadata:
    name: adtrack-flask-api-service # Name of the service
spec:
    selector:
        app: adtrack-flask-api # Matches the app label in the deployment
    ports:
        - protocol: TCP
          port: 5000 # Port exposed to the host
          targetPort: 5000 # Port inside the container
    type: NodePort # Expose the service on a high port
